### ISSUE TITLE
Command splitter option does not work in nest config

### ISSUE THREAD

**Issue by anlifeng2008** [sipwise/klish#1]
Command splitter option does not work in nest config. 
I want to insert a "!" between to nest entry, for example bgp address-family..., but splitter option does not work, can some one help me?

thanks a lot!

**Comment by anlifeng2008** [comment]
or someone can tell me how to dump the config in konfd by konf? pls give me a example, thanks again

**Comment by taurus-forever** [comment]
Hi,

Sipwise doesn't provide any support to klish,
maybe you should address your questions to upstream:
http://libcode.org/projects/klish/ ?

**Comment by anlifeng2008** [comment]
@taurus-forever thanks very much！
